# coding: utf-8

"""
    demo_app

    demo_app  # noqa: E501

    The version of the OpenAPI document: 2.198.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_demo_app_web_api_tank_controller_create(self):
        """Test case for demo_app_web_api_tank_controller_create

        Create a new tank on the specified site   # noqa: E501
        """
        pass

    def test_demo_app_web_api_tank_controller_index(self):
        """Test case for demo_app_web_api_tank_controller_index

        List all tanks visible to the user   # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
