# coding: utf-8

# flake8: noqa
"""
    demo

    validere  # noqa: E501

    The version of the OpenAPI document: 2.198.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.bad_request import BadRequest
from openapi_client.models.not_found import NotFound
from openapi_client.models.tank import Tank
from openapi_client.models.tank_request import TankRequest
from openapi_client.models.unauthorized import Unauthorized
